#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import pickle
import argparse
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import seaborn as sns

def calculate_sequence_lengths(dataset_file):
    """
    Calculate the length of each sequence in the dataset
    
    Args:
        dataset_file: Pickle file path generated by asm_dataset_generator.py
        
    Returns:
        sequence_lengths: List containing lengths of all sequences
    """
    print(f"Loading dataset: {dataset_file}")
    with open(dataset_file, 'rb') as f:
        dataset = pickle.load(f)
    
    print(f"Dataset contains {len(dataset)} sequences")
    
    sequence_lengths = []
    
    # Use tqdm to display progress bar
    for sequence in tqdm(dataset, desc="Calculating sequence lengths"):
        # Calculate the total number of all tokens in all instructions in the sequence
        total_tokens = 0
        for instruction_tokens in sequence:
            total_tokens += len(instruction_tokens)
        
        sequence_lengths.append(total_tokens)
    
    return sequence_lengths

def analyze_lengths(sequence_lengths):
    """
    Analyze the statistical characteristics of sequence lengths
    
    Args:
        sequence_lengths: List containing all sequence lengths
        
    Returns:
        stats: Dictionary containing statistical information
    """
    stats = {
        "count": len(sequence_lengths),
        "min": min(sequence_lengths),
        "max": max(sequence_lengths),
        "mean": np.mean(sequence_lengths),
        "median": np.median(sequence_lengths),
        "std": np.std(sequence_lengths),
        "percentiles": {
            "10": np.percentile(sequence_lengths, 10),
            "25": np.percentile(sequence_lengths, 25),
            "50": np.percentile(sequence_lengths, 50),
            "75": np.percentile(sequence_lengths, 75),
            "90": np.percentile(sequence_lengths, 90),
            "95": np.percentile(sequence_lengths, 95),
            "99": np.percentile(sequence_lengths, 99),
        }
    }
    
    return stats

def plot_distribution(sequence_lengths, output_file=None):
    """
    Plot the distribution of sequence lengths
    
    Args:
        sequence_lengths: List containing all sequence lengths
        output_file: Output image file path, if None then display the image
    """
    # Set English font and style
    plt.style.use('seaborn-v0_8-whitegrid')
    plt.rcParams['font.family'] = 'DejaVu Sans'
    
    # Create subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))
    
    # Plot histogram
    sns.histplot(sequence_lengths, kde=True, ax=ax1)
    ax1.set_title("Sequence Length Distribution Histogram")
    ax1.set_xlabel("Sequence Length (tokens)")
    ax1.set_ylabel("Frequency")
    
    # Plot box plot
    sns.boxplot(y=sequence_lengths, ax=ax2)
    ax2.set_title("Sequence Length Box Plot")
    ax2.set_ylabel("Sequence Length (tokens)")
    
    # Add some statistical information
    stats = analyze_lengths(sequence_lengths)
    textstr = '\n'.join((
        f"Sample Count: {stats['count']}",
        f"Min: {stats['min']:.2f}",
        f"Max: {stats['max']:.2f}",
        f"Mean: {stats['mean']:.2f}",
        f"Median: {stats['median']:.2f}",
        f"Std Dev: {stats['std']:.2f}",
        f"95th Percentile: {stats['percentiles']['95']:.2f}",
        f"99th Percentile: {stats['percentiles']['99']:.2f}",
    ))
    
    props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
    ax2.text(0.05, 0.95, textstr, transform=ax2.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)
    
    plt.tight_layout()
    
    # If output file path is provided, save the image
    if output_file:
        # Check file extension, if .pdf then save as PDF format
        if output_file.lower().endswith('.pdf'):
            plt.savefig(output_file, format='pdf', dpi=300, bbox_inches='tight')
        else:
            # Add extension check to ensure other formats can also be saved correctly
            plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Image saved to: {output_file}")
    else:
        plt.show()

def main():
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Analyze sequence length distribution')
    parser.add_argument('dataset', help='Pickle file path generated by asm_dataset_generator.py')
    parser.add_argument('-o', '--output', help='Output image file path (supports .pdf format)')
    parser.add_argument('--csv', help='Output CSV file path')
    parser.add_argument('--no-plot', action='store_true', help='Do not generate charts, only output statistical information')
    
    args = parser.parse_args()
    
    # Calculate sequence lengths
    sequence_lengths = calculate_sequence_lengths(args.dataset)
    
    # Analyze length distribution
    stats = analyze_lengths(sequence_lengths)
    
    # Output statistical information
    print("\nSequence length statistics:")
    print(f"Sample count: {stats['count']}")
    print(f"Minimum: {stats['min']}")
    print(f"Maximum: {stats['max']}")
    print(f"Mean: {stats['mean']:.2f}")
    print(f"Median: {stats['median']:.2f}")
    print(f"Standard deviation: {stats['std']:.2f}")
    print("\nPercentiles:")
    for percentile, value in stats['percentiles'].items():
        print(f"{percentile}%: {value:.2f}")
    
    # If needed, output CSV file
    if args.csv:
        import csv
        with open(args.csv, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(['Sequence Length'])
            for length in sequence_lengths:
                writer.writerow([length])
        print(f"\nSequence length data saved to: {args.csv}")
    
    # If needed, plot distribution
    if not args.no_plot:
        plot_distribution(sequence_lengths, args.output)

if __name__ == "__main__":
    main()